name: rf_extensions
description: Filling the missing features of dart sdk and third-party libraries.
version: 0.0.1
repository: https://github.com/Ragibn5/rf_extensions.git

environment:
  sdk: ^3.0.6

# Add regular dependencies here.
dependencies:
  path: ^1.8.0
  get_it: ^8.0.2
  dartz: ^0.10.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
